name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/setup-nasm@v1
    - uses: egor-tensin/setup-gcc@v1
    
    - name: Run build
      run:  make
      
    - name: Post codecov
      run: bash <(curl -s https://codecov.io/bash)
